### PR TITLE
Feature/xml migration

### PR DESCRIPTION
**Pull request by damthor**
Added script for migrating old-style diagrams by refactoring the xml structure.
Gets executed before parsing so all elements get stored correctly.

### CODE REVIEW

**Review by LouisMoreaux — APPROVED** [review]
Tested XML migration from 21.1 for
- User Task
- Service Task
- Script Task
All attributes are correctly migrated inside the extensionElements tag

**Comment by commi235** [comment]
I would opt for using a procedure with in out for the xml and an out parameter to return if any change happened.
Using "in out" or "out" parameters with a function is considered bad practice.
Furthermore a function can normally be called from SQL, put if it has any out parameter this isn't true anymore.
To avoid confusion move the implementation to being a procedure.

**Comment by damthor** [comment]
Changed procedure to function as described in https://github.com/mt-ag/apex-flowsforapex/pull/381/commits/fd83071134cdf8377303bc69188d04630b81199b.
Also added a check of the exporter name to prevent migrating diagrams that have been exported from another platform (e.g. Camunda Modeler). Exporter will be set when saving inside the F4A Modeler.

**Review by commi235 — APPROVED** [review]

**Comment by LouisMoreaux** [comment]
Testing the XML migration again with the new procedure. All attributes are correctly moved inside the extensionElements tag

**Pull request merged**
